### ISSUE TITLE
Linux implementation for sctp_shutack_wait_bound

### ISSUE THREAD

**Issue by nhanth87** [sctp/lksctp-tools#29]
Hi team,
I found that linux is not implemented the parameter `sctp_shutack_wait_bound`.
Do we have any other parameter that can do the same with `sctp_shutack_wait_bound`?

Br,
TN

**Comment by marceloleitner** [comment]
Hi TN,
That's https://docs.oracle.com/cd/E19253-01/817-0404/chapter4-95/index.html , right?

If yes then I think that's about:
https://tools.ietf.org/html/rfc4960#section-9.2
   The sender of the SHUTDOWN MAY also start an overall guard timer
   'T5-shutdown-guard' to bound the overall time for the shutdown
   sequence.  At the expiration of this timer, the sender SHOULD abort
   the association by sending an ABORT chunk.  If the 'T5-shutdown-
   guard' timer is used, it SHOULD be set to the recommended value of 5
   times 'RTO.Max'.

We have it that procedure, but not easily tunable. Currently the only way to tune it on Linux is by tuning RTO.Max. And please note that it is initialized only when initializing the association, so it had to be done before that in order to take effect.
Does that help?
