### ISSUE TITLE
The library version is still 1.0.19 in 1.0.20

### ISSUE THREAD

**Issue by yizhao1** [sctp/lksctp-tools#62]
Build lksctp-tools 1.0.20, the library version is still 1.0.19:
$ ls /usr/lib/libsctip.so*
libsctp.so  libsctp.so.1  libsctp.so.1.0.19

$ ls /usr/lib/lksctp-tools/libwithsctip.so*
lksctp-tools/libwithsctp.so  lksctp-tools/libwithsctp.so.1  lksctp-tools/libwithsctp.so.1.0.19

Need to update the version in configure.ac.

**Comment by laf0rge** [comment]
Indeed, even today in master, configure.ac still specifies 1.0.19 as version number.

However, the even more confusing fact is that the source code release version is used as LIBVERSION.  This doesn't make sense at all, libtool library versioning is completely disjunct and works on the current/reivison/age system, see https://www.gnu.org/software/libtool/manual/html_node/Libtool-versioning.html

So the LIBSCTP_{CURRENT,REVISION_AGE} should be incremented exclusively in accordance with https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html as otherwise binary library compatibility across versions will never work...

**Comment by lxin** [comment]
A commit "Release lksctp-tools-1.0.20" is created to fix it, and based on this commit, tag: v1.0.20 and tag: lksctp-tools-1.0.20 are recreated.

311fcde (HEAD -> master, tag: v1.0.20, tag: lksctp-tools-1.0.20, origin/master, origin/HEAD) Release lksctp-tools-1.0.20

Please check, thanks for the report.

**Comment by yizhao1** [comment]
Thanks. The version is correct now.

**Comment by trofi** [comment]
`nixpkgs` attempted to package the old release and noticed hash change after retagging the release (https://github.com/NixOS/nixpkgs/pull/344326#issuecomment-2373055191).

If `nixpkgs` was able to mirror the tarballs before retagging we would not ever notice the update.

I suspect some other distributions might be already affected. My suggestion is to issue another release and treat tags as immutable.

**Comment by lxin** [comment]
@trofi I can't revert the 1.0.20 tag to the old one, as there may be already people using the new hash. Besides, even if I revert the tag back, the hash will never be the same.

I will let it be and issue a new tag 1.0.21 as you suggested, and assume people will upgrade again, to this new version that will be good.  Does this sound okay to you?

**Comment by trofi** [comment]
Adding a new tag and release sounds perfect! Thank you!
